server:
  port: 8080
spring:
  application:
    name: api-gateway
  # configuraciones ruteo
  cloud:
    gateway:
      mvc:
        routes:
          - id: catalogRoute
            uri: lb://catalog-service
            predicates:
              - Path=/catalog/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}